import type { VendorCategory, CommitteeMemberRole, ParkingSpotType, ParkingSpotStatus, UserRole, Environment, PricingTier } from "./types";

export const APP_NAME = "ResiGate";

// User roles - New RBAC System
export const USER_ROLES = {
  // Platform-wide roles
  OWNER_APP: 'owner_app',           // Super admin — controls entire platform
  OPS: 'ops',                       // Internal support & operations team
  
  // Society-level roles
  SOCIETY_ADMIN: 'society_admin',   // Committee/admin role for society management
  GUARD: 'guard',                   // Security user with simplified interface
  
  // Resident-level roles (per flat)
  OWNER_RESIDENT: 'owner_resident', // Flat owner
  RENTER_RESIDENT: 'renter_resident', // Tenant
  MEMBER_RESIDENT: 'member_resident', // Family or related members
  
  // Support roles
  STAFF: 'staff',                   // Maid/Driver/Cook (configurable login)
  API_SYSTEM: 'api_system',         // For system integrations
  
  // Legacy roles for backward compatibility
  SUPERADMIN: 'owner_app',          // Maps to OWNER_APP
  OWNER: 'owner_resident',          // Maps to OWNER_RESIDENT
  RENTER: 'renter_resident',        // Maps to RENTER_RESIDENT
} as const;

// Role groups for easier management
export const ROLE_GROUPS = {
  PLATFORM_ADMIN: [USER_ROLES.OWNER_APP, USER_ROLES.OPS],
  SOCIETY_ADMIN: [USER_ROLES.SOCIETY_ADMIN, USER_ROLES.GUARD],
  RESIDENT: [USER_ROLES.OWNER_RESIDENT, USER_ROLES.RENTER_RESIDENT, USER_ROLES.MEMBER_RESIDENT],
  SUPPORT: [USER_ROLES.STAFF, USER_ROLES.API_SYSTEM],
} as const;

// Group names for display
export const ROLE_GROUP_NAMES = {
  PLATFORM_ADMIN: 'Platform Admin',
  SOCIETY_ADMIN: 'Society Admin', 
  RESIDENT: 'Resident',
  SUPPORT: 'Support',
} as const;

// Map roles to groups
export const ROLE_TO_GROUP = {
  [USER_ROLES.OWNER_APP]: 'PLATFORM_ADMIN',
  [USER_ROLES.OPS]: 'PLATFORM_ADMIN',
  [USER_ROLES.SOCIETY_ADMIN]: 'SOCIETY_ADMIN',
  [USER_ROLES.GUARD]: 'SOCIETY_ADMIN',
  [USER_ROLES.OWNER_RESIDENT]: 'RESIDENT',
  [USER_ROLES.RENTER_RESIDENT]: 'RESIDENT',
  [USER_ROLES.MEMBER_RESIDENT]: 'RESIDENT',
  [USER_ROLES.STAFF]: 'SUPPORT',
  [USER_ROLES.API_SYSTEM]: 'SUPPORT',
} as const;

// Roles that can login to the main application
export const LOGIN_ELIGIBLE_ROLES = [
  USER_ROLES.OWNER_APP,
  USER_ROLES.OPS,
  USER_ROLES.SOCIETY_ADMIN,
  USER_ROLES.GUARD,
  USER_ROLES.OWNER_RESIDENT,
  USER_ROLES.RENTER_RESIDENT,
  USER_ROLES.MEMBER_RESIDENT,
  USER_ROLES.STAFF,
  USER_ROLES.API_SYSTEM,
  // Add these aliases for broader demo/testing support
  'platform_admin',
  'support',
  'resident',
] as const;

// Roles selectable during registration (excluding platform admin roles)
export const SELECTABLE_USER_ROLES = [
  USER_ROLES.SOCIETY_ADMIN,
  USER_ROLES.GUARD,
  USER_ROLES.OWNER_RESIDENT,
  USER_ROLES.RENTER_RESIDENT,
  USER_ROLES.MEMBER_RESIDENT,
] as const;

// Role hierarchy for permission inheritance
export const ROLE_HIERARCHY = {
  [USER_ROLES.OWNER_APP]: 1000,
  [USER_ROLES.OPS]: 900,
  [USER_ROLES.SOCIETY_ADMIN]: 800,
  [USER_ROLES.OWNER_RESIDENT]: 700,
  [USER_ROLES.RENTER_RESIDENT]: 600,
  [USER_ROLES.MEMBER_RESIDENT]: 500,
  [USER_ROLES.GUARD]: 400,
  [USER_ROLES.STAFF]: 300,
  [USER_ROLES.API_SYSTEM]: 200,
} as const;


export const LOCAL_STORAGE_KEYS = {
  USERS: "resiGateUsers",
  VISITORS: "resiGateVisitors",
  LOGGED_IN_USER: "resiGateLoggedInUser",
};

// Feature Flag System Constants
export const ENVIRONMENTS = {
  DEV: 'dev',
  PROD: 'prod', 
  DEMO: 'demo',
} as const;

export const PRICING_TIERS = {
  FREE: 'free',
  PREMIUM: 'premium',
  ENTERPRISE: 'enterprise',
} as const;

// Current environment (should be set via environment variable)
export const CURRENT_ENVIRONMENT = (process.env.NODE_ENV === 'production' ? 
  (process.env.NEXT_PUBLIC_APP_ENV || 'prod') : 'dev') as Environment;


export const VISIT_PURPOSES = [
  "Delivery",
  "Guest Visit",
  "Maintenance/Service",
  "Enquiry",
  "Staff/Employee",
  "Cab/Taxi",
  "Sales/Vendor",
  "Interview",
  "Other",
] as const;

export const PUBLIC_ENTRY_SOURCE = "PUBLIC_QR_SCAN";

export const GATE_PASS_STATUSES_ARRAY = ["Pending", "Used", "Cancelled", "Expired"] as const;

export const DEFAULT_ITEMS_PER_PAGE = 10;


export const COMPLAINT_STATUSES = [ // Renamed for clarity
  "Open",
  "In Progress",
  "Resolved",
  "Closed",
] as const;

export const COMPLAINT_CATEGORIES_LIST = [
  "Maintenance",
  "Security",
  "Noise",
  "Parking",
  "Cleanliness",
  "Staff Behavior",
  "Common Area",
  "Pet Related",
  "Other",
] as const;

export const VENDOR_CATEGORIES = [
  "Plumber",
  "Electrician",
  "Carpenter",
  "Painter",
  "Groceries",
  "Milk Delivery",
  "Newspaper Delivery",
  "Laundry",
  "House Keeping",
  "Cook/Chef",
  "Pest Control",
  "Internet Provider",
  "Cable TV",
  "AC Repair",
  "Appliance Repair",
  "Pharmacy",
  "Doctor/Clinic",
  "Tiffin Service",
  "Other Services",
] as const;

export const COMMITTEE_MEMBER_ROLES = [
  "President",
  "Vice-President",
  "Secretary",
  "Joint-Secretary",
  "Treasurer",
  "Committee Member",
  "Advisor",
  "Other",
] as const;

// Parking Management Constants
export const PARKING_SPOT_TYPES = ["car", "bike"] as const;
export const PARKING_SPOT_STATUSES = ["available", "allocated"] as const;

// Reverted Security Log constants
// export const SECURITY_INCIDENT_SEVERITIES = ["Low", "Medium", "High"] as const;
// export const SECURITY_INCIDENT_STATUSES = ["New", "Under Review", "Action Taken", "Resolved", "Closed"] as const;

export const HELP_DESK_CATEGORIES = [
  'Accounts',
  'Complaint against a Resident',
  'Caltural/Social activities',
  'Data Management',
  'Electrical, Lift',
  'Gardening',
  'Gym, sports',
  'House Keeping',
  'No Dues Certificate',
  'Others',
  'Plumbing',
  'Security',
] as const;

// RBAC Feature Management Constants
export const FEATURES = {
  // Visitor Management
  VISITOR_MANAGEMENT: 'visitor_management',
  VISITOR_CREATE: 'visitor_create',
  VISITOR_READ: 'visitor_read',
  VISITOR_UPDATE: 'visitor_update',
  VISITOR_DELETE: 'visitor_delete',
  VISITOR_APPROVE: 'visitor_approve',
  
  // Gate Pass Management
  GATE_PASS_MANAGEMENT: 'gate_pass_management',
  GATE_PASS_CREATE: 'gate_pass_create',
  GATE_PASS_READ: 'gate_pass_read',
  GATE_PASS_UPDATE: 'gate_pass_update',
  GATE_PASS_DELETE: 'gate_pass_delete',
  
  // Billing Management
  BILLING_MANAGEMENT: 'billing_management',
  BILLING_CREATE: 'billing_create',
  BILLING_READ: 'billing_read',
  BILLING_UPDATE: 'billing_update',
  BILLING_DELETE: 'billing_delete',
  BILLING_CONFIG: 'billing_config',
  
  // Facility Management
  FACILITY_MANAGEMENT: 'facility_management',
  FACILITY_CREATE: 'facility_create',
  FACILITY_READ: 'facility_read',
  FACILITY_UPDATE: 'facility_update',
  FACILITY_DELETE: 'facility_delete',
  FACILITY_BOOKING: 'facility_booking',
  
  // Parking Management
  PARKING_MANAGEMENT: 'parking_management',
  PARKING_CREATE: 'parking_create',
  PARKING_READ: 'parking_read',
  PARKING_UPDATE: 'parking_update',
  PARKING_DELETE: 'parking_delete',
  PARKING_ASSIGN: 'parking_assign',
  
  // User Management
  USER_MANAGEMENT: 'user_management',
  USER_CREATE: 'user_create',
  USER_READ: 'user_read',
  USER_UPDATE: 'user_update',
  USER_DELETE: 'user_delete',
  USER_APPROVE: 'user_approve',
  
  // Committee Management
  COMMITTEE_MANAGEMENT: 'committee_management',
  COMMITTEE_CREATE: 'committee_create',
  COMMITTEE_READ: 'committee_read',
  COMMITTEE_UPDATE: 'committee_update',
  COMMITTEE_DELETE: 'committee_delete',
  
  // Notice Management
  NOTICE_MANAGEMENT: 'notice_management',
  NOTICE_CREATE: 'notice_create',
  NOTICE_READ: 'notice_read',
  NOTICE_UPDATE: 'notice_update',
  NOTICE_DELETE: 'notice_delete',
  
  // HelpDesk Management
  HELPDESK_MANAGEMENT: 'helpdesk_management',
  HELPDESK_CREATE: 'helpdesk_create',
  HELPDESK_READ: 'helpdesk_read',
  HELPDESK_UPDATE: 'helpdesk_update',
  HELPDESK_DELETE: 'helpdesk_delete',
  HELPDESK_RESOLVE: 'helpdesk_resolve',
  
  // Meeting Management
  MEETING_MANAGEMENT: 'meeting_management',
  MEETING_CREATE: 'meeting_create',
  MEETING_READ: 'meeting_read',
  MEETING_UPDATE: 'meeting_update',
  MEETING_DELETE: 'meeting_delete',
  
  // Dashboard Access
  DASHBOARD_ADMIN: 'dashboard_admin',
  DASHBOARD_GUARD: 'dashboard_guard',
  DASHBOARD_RESIDENT: 'dashboard_resident',
  
  // Settings Management
  SETTINGS_MANAGEMENT: 'settings_management',
  SETTINGS_PAYMENT: 'settings_payment',
  SETTINGS_SOCIETY: 'settings_society',
  
  // Impersonation
  IMPERSONATION: 'impersonation',
  
  // Staff Management
  STAFF_MANAGEMENT: 'staff_management',
  STAFF_LOGIN: 'staff_login',
  
  // SOS/Emergency
  SOS_MANAGEMENT: 'sos_management',
  SOS_CREATE: 'sos_create',
  SOS_READ: 'sos_read',
  SOS_RESPOND: 'sos_respond',
} as const;

// Feature-to-tier mapping for pricing controls
export const FEATURE_TO_TIER = {
  // FREE tier features
  [FEATURES.VISITOR_MANAGEMENT]: PRICING_TIERS.FREE,
  [FEATURES.VISITOR_CREATE]: PRICING_TIERS.FREE,
  [FEATURES.VISITOR_READ]: PRICING_TIERS.FREE,
  [FEATURES.VISITOR_UPDATE]: PRICING_TIERS.FREE,
  [FEATURES.VISITOR_DELETE]: PRICING_TIERS.FREE,
  [FEATURES.VISITOR_APPROVE]: PRICING_TIERS.FREE,
  [FEATURES.GATE_PASS_MANAGEMENT]: PRICING_TIERS.FREE,
  [FEATURES.GATE_PASS_CREATE]: PRICING_TIERS.FREE,
  [FEATURES.GATE_PASS_READ]: PRICING_TIERS.FREE,
  [FEATURES.GATE_PASS_UPDATE]: PRICING_TIERS.FREE,
  [FEATURES.GATE_PASS_DELETE]: PRICING_TIERS.FREE,
  [FEATURES.DASHBOARD_ADMIN]: PRICING_TIERS.FREE,
  [FEATURES.DASHBOARD_GUARD]: PRICING_TIERS.FREE,
  [FEATURES.DASHBOARD_RESIDENT]: PRICING_TIERS.FREE,
  [FEATURES.NOTICE_MANAGEMENT]: PRICING_TIERS.FREE,
  [FEATURES.NOTICE_CREATE]: PRICING_TIERS.FREE,
  [FEATURES.NOTICE_READ]: PRICING_TIERS.FREE,
  [FEATURES.NOTICE_UPDATE]: PRICING_TIERS.FREE,
  [FEATURES.NOTICE_DELETE]: PRICING_TIERS.FREE,
  [FEATURES.SOS_MANAGEMENT]: PRICING_TIERS.FREE,
  [FEATURES.SOS_CREATE]: PRICING_TIERS.FREE,
  [FEATURES.SOS_READ]: PRICING_TIERS.FREE,
  [FEATURES.SOS_RESPOND]: PRICING_TIERS.FREE,
  
  // PREMIUM tier features  
  [FEATURES.BILLING_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.BILLING_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.BILLING_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.BILLING_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.BILLING_DELETE]: PRICING_TIERS.PREMIUM,
  [FEATURES.BILLING_CONFIG]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_DELETE]: PRICING_TIERS.PREMIUM,
  [FEATURES.FACILITY_BOOKING]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_DELETE]: PRICING_TIERS.PREMIUM,
  [FEATURES.PARKING_ASSIGN]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_DELETE]: PRICING_TIERS.PREMIUM,
  [FEATURES.HELPDESK_RESOLVE]: PRICING_TIERS.PREMIUM,
  [FEATURES.MEETING_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.MEETING_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.MEETING_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.MEETING_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.MEETING_DELETE]: PRICING_TIERS.PREMIUM,
  [FEATURES.COMMITTEE_MANAGEMENT]: PRICING_TIERS.PREMIUM,
  [FEATURES.COMMITTEE_CREATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.COMMITTEE_READ]: PRICING_TIERS.PREMIUM,
  [FEATURES.COMMITTEE_UPDATE]: PRICING_TIERS.PREMIUM,
  [FEATURES.COMMITTEE_DELETE]: PRICING_TIERS.PREMIUM,
  
  // ENTERPRISE tier features
  [FEATURES.USER_MANAGEMENT]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.USER_CREATE]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.USER_READ]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.USER_UPDATE]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.USER_DELETE]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.USER_APPROVE]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.SETTINGS_MANAGEMENT]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.SETTINGS_PAYMENT]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.SETTINGS_SOCIETY]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.IMPERSONATION]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.STAFF_MANAGEMENT]: PRICING_TIERS.ENTERPRISE,
  [FEATURES.STAFF_LOGIN]: PRICING_TIERS.ENTERPRISE,
} as const;

// Feature categories for UI organization
export const FEATURE_CATEGORIES = {
  VISITOR: 'Visitor Management',
  BILLING: 'Billing & Payments',
  FACILITY: 'Facility Management',
  PARKING: 'Parking Management',
  USER: 'User Management',
  COMMITTEE: 'Committee Management',
  NOTICE: 'Notice Management',
  HELPDESK: 'HelpDesk Management',
  MEETING: 'Meeting Management',
  DASHBOARD: 'Dashboard Access',
  SETTINGS: 'Settings Management',
  ADMIN: 'Admin Features',
  EMERGENCY: 'Emergency Features',
} as const;

// Map features to categories
export const FEATURE_TO_CATEGORY = {
  [FEATURES.VISITOR_MANAGEMENT]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.VISITOR_CREATE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.VISITOR_READ]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.VISITOR_UPDATE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.VISITOR_DELETE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.VISITOR_APPROVE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.GATE_PASS_MANAGEMENT]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.GATE_PASS_CREATE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.GATE_PASS_READ]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.GATE_PASS_UPDATE]: FEATURE_CATEGORIES.VISITOR,
  [FEATURES.GATE_PASS_DELETE]: FEATURE_CATEGORIES.VISITOR,
  
  [FEATURES.BILLING_MANAGEMENT]: FEATURE_CATEGORIES.BILLING,
  [FEATURES.BILLING_CREATE]: FEATURE_CATEGORIES.BILLING,
  [FEATURES.BILLING_READ]: FEATURE_CATEGORIES.BILLING,
  [FEATURES.BILLING_UPDATE]: FEATURE_CATEGORIES.BILLING,
  [FEATURES.BILLING_DELETE]: FEATURE_CATEGORIES.BILLING,
  [FEATURES.BILLING_CONFIG]: FEATURE_CATEGORIES.BILLING,
  
  [FEATURES.FACILITY_MANAGEMENT]: FEATURE_CATEGORIES.FACILITY,
  [FEATURES.FACILITY_CREATE]: FEATURE_CATEGORIES.FACILITY,
  [FEATURES.FACILITY_READ]: FEATURE_CATEGORIES.FACILITY,
  [FEATURES.FACILITY_UPDATE]: FEATURE_CATEGORIES.FACILITY,
  [FEATURES.FACILITY_DELETE]: FEATURE_CATEGORIES.FACILITY,
  [FEATURES.FACILITY_BOOKING]: FEATURE_CATEGORIES.FACILITY,
  
  [FEATURES.PARKING_MANAGEMENT]: FEATURE_CATEGORIES.PARKING,
  [FEATURES.PARKING_CREATE]: FEATURE_CATEGORIES.PARKING,
  [FEATURES.PARKING_READ]: FEATURE_CATEGORIES.PARKING,
  [FEATURES.PARKING_UPDATE]: FEATURE_CATEGORIES.PARKING,
  [FEATURES.PARKING_DELETE]: FEATURE_CATEGORIES.PARKING,
  [FEATURES.PARKING_ASSIGN]: FEATURE_CATEGORIES.PARKING,
  
  [FEATURES.USER_MANAGEMENT]: FEATURE_CATEGORIES.USER,
  [FEATURES.USER_CREATE]: FEATURE_CATEGORIES.USER,
  [FEATURES.USER_READ]: FEATURE_CATEGORIES.USER,
  [FEATURES.USER_UPDATE]: FEATURE_CATEGORIES.USER,
  [FEATURES.USER_DELETE]: FEATURE_CATEGORIES.USER,
  [FEATURES.USER_APPROVE]: FEATURE_CATEGORIES.USER,
  
  [FEATURES.COMMITTEE_MANAGEMENT]: FEATURE_CATEGORIES.COMMITTEE,
  [FEATURES.COMMITTEE_CREATE]: FEATURE_CATEGORIES.COMMITTEE,
  [FEATURES.COMMITTEE_READ]: FEATURE_CATEGORIES.COMMITTEE,
  [FEATURES.COMMITTEE_UPDATE]: FEATURE_CATEGORIES.COMMITTEE,
  [FEATURES.COMMITTEE_DELETE]: FEATURE_CATEGORIES.COMMITTEE,
  
  [FEATURES.NOTICE_MANAGEMENT]: FEATURE_CATEGORIES.NOTICE,
  [FEATURES.NOTICE_CREATE]: FEATURE_CATEGORIES.NOTICE,
  [FEATURES.NOTICE_READ]: FEATURE_CATEGORIES.NOTICE,
  [FEATURES.NOTICE_UPDATE]: FEATURE_CATEGORIES.NOTICE,
  [FEATURES.NOTICE_DELETE]: FEATURE_CATEGORIES.NOTICE,
  
  [FEATURES.HELPDESK_MANAGEMENT]: FEATURE_CATEGORIES.HELPDESK,
  [FEATURES.HELPDESK_CREATE]: FEATURE_CATEGORIES.HELPDESK,
  [FEATURES.HELPDESK_READ]: FEATURE_CATEGORIES.HELPDESK,
  [FEATURES.HELPDESK_UPDATE]: FEATURE_CATEGORIES.HELPDESK,
  [FEATURES.HELPDESK_DELETE]: FEATURE_CATEGORIES.HELPDESK,
  [FEATURES.HELPDESK_RESOLVE]: FEATURE_CATEGORIES.HELPDESK,
  
  [FEATURES.MEETING_MANAGEMENT]: FEATURE_CATEGORIES.MEETING,
  [FEATURES.MEETING_CREATE]: FEATURE_CATEGORIES.MEETING,
  [FEATURES.MEETING_READ]: FEATURE_CATEGORIES.MEETING,
  [FEATURES.MEETING_UPDATE]: FEATURE_CATEGORIES.MEETING,
  [FEATURES.MEETING_DELETE]: FEATURE_CATEGORIES.MEETING,
  
  [FEATURES.DASHBOARD_ADMIN]: FEATURE_CATEGORIES.DASHBOARD,
  [FEATURES.DASHBOARD_GUARD]: FEATURE_CATEGORIES.DASHBOARD,
  [FEATURES.DASHBOARD_RESIDENT]: FEATURE_CATEGORIES.DASHBOARD,
  
  [FEATURES.SETTINGS_MANAGEMENT]: FEATURE_CATEGORIES.SETTINGS,
  [FEATURES.SETTINGS_PAYMENT]: FEATURE_CATEGORIES.SETTINGS,
  [FEATURES.SETTINGS_SOCIETY]: FEATURE_CATEGORIES.SETTINGS,
  
  [FEATURES.IMPERSONATION]: FEATURE_CATEGORIES.ADMIN,
  [FEATURES.STAFF_MANAGEMENT]: FEATURE_CATEGORIES.ADMIN,
  [FEATURES.STAFF_LOGIN]: FEATURE_CATEGORIES.ADMIN,
  
  [FEATURES.SOS_MANAGEMENT]: FEATURE_CATEGORIES.EMERGENCY,
  [FEATURES.SOS_CREATE]: FEATURE_CATEGORIES.EMERGENCY,
  [FEATURES.SOS_READ]: FEATURE_CATEGORIES.EMERGENCY,
  [FEATURES.SOS_RESPOND]: FEATURE_CATEGORIES.EMERGENCY,
} as const;

// Default permissions for each role
export const DEFAULT_ROLE_PERMISSIONS = {
  [USER_ROLES.OWNER_APP]: Object.values(FEATURES), // All permissions
  [USER_ROLES.OPS]: Object.values(FEATURES), // All permissions
  
  [USER_ROLES.SOCIETY_ADMIN]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_CREATE, FEATURES.VISITOR_READ, FEATURES.VISITOR_UPDATE, FEATURES.VISITOR_DELETE, FEATURES.VISITOR_APPROVE,
    FEATURES.GATE_PASS_MANAGEMENT, FEATURES.GATE_PASS_CREATE, FEATURES.GATE_PASS_READ, FEATURES.GATE_PASS_UPDATE, FEATURES.GATE_PASS_DELETE,
    FEATURES.BILLING_MANAGEMENT, FEATURES.BILLING_CREATE, FEATURES.BILLING_READ, FEATURES.BILLING_UPDATE, FEATURES.BILLING_DELETE, FEATURES.BILLING_CONFIG,
    FEATURES.FACILITY_MANAGEMENT, FEATURES.FACILITY_CREATE, FEATURES.FACILITY_READ, FEATURES.FACILITY_UPDATE, FEATURES.FACILITY_DELETE, FEATURES.FACILITY_BOOKING,
    FEATURES.PARKING_MANAGEMENT, FEATURES.PARKING_CREATE, FEATURES.PARKING_READ, FEATURES.PARKING_UPDATE, FEATURES.PARKING_DELETE, FEATURES.PARKING_ASSIGN,
    FEATURES.USER_MANAGEMENT, FEATURES.USER_CREATE, FEATURES.USER_READ, FEATURES.USER_UPDATE, FEATURES.USER_DELETE, FEATURES.USER_APPROVE,
    FEATURES.COMMITTEE_MANAGEMENT, FEATURES.COMMITTEE_CREATE, FEATURES.COMMITTEE_READ, FEATURES.COMMITTEE_UPDATE, FEATURES.COMMITTEE_DELETE,
    FEATURES.NOTICE_MANAGEMENT, FEATURES.NOTICE_CREATE, FEATURES.NOTICE_READ, FEATURES.NOTICE_UPDATE, FEATURES.NOTICE_DELETE,
    FEATURES.HELPDESK_MANAGEMENT, FEATURES.HELPDESK_CREATE, FEATURES.HELPDESK_READ, FEATURES.HELPDESK_UPDATE, FEATURES.HELPDESK_DELETE, FEATURES.HELPDESK_RESOLVE,
    FEATURES.MEETING_MANAGEMENT, FEATURES.MEETING_CREATE, FEATURES.MEETING_READ, FEATURES.MEETING_UPDATE, FEATURES.MEETING_DELETE,
    FEATURES.DASHBOARD_ADMIN,
    FEATURES.SETTINGS_MANAGEMENT, FEATURES.SETTINGS_PAYMENT, FEATURES.SETTINGS_SOCIETY,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE, FEATURES.SOS_READ, FEATURES.SOS_RESPOND,
  ],
  
  [USER_ROLES.GUARD]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_CREATE, FEATURES.VISITOR_READ, FEATURES.VISITOR_UPDATE, FEATURES.VISITOR_APPROVE,
    FEATURES.GATE_PASS_MANAGEMENT, FEATURES.GATE_PASS_READ,
    FEATURES.DASHBOARD_GUARD,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE, FEATURES.SOS_READ, FEATURES.SOS_RESPOND,
  ],
  
  [USER_ROLES.OWNER_RESIDENT]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_CREATE, FEATURES.VISITOR_READ, FEATURES.VISITOR_UPDATE, FEATURES.VISITOR_DELETE,
    FEATURES.GATE_PASS_MANAGEMENT, FEATURES.GATE_PASS_CREATE, FEATURES.GATE_PASS_READ,
    FEATURES.BILLING_MANAGEMENT, FEATURES.BILLING_READ,
    FEATURES.FACILITY_MANAGEMENT, FEATURES.FACILITY_READ, FEATURES.FACILITY_BOOKING,
    FEATURES.PARKING_MANAGEMENT, FEATURES.PARKING_READ,
    FEATURES.NOTICE_MANAGEMENT, FEATURES.NOTICE_READ,
    FEATURES.HELPDESK_MANAGEMENT, FEATURES.HELPDESK_CREATE, FEATURES.HELPDESK_READ, FEATURES.HELPDESK_UPDATE,
    FEATURES.MEETING_MANAGEMENT, FEATURES.MEETING_READ,
    FEATURES.DASHBOARD_RESIDENT,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE,
  ],
  
  [USER_ROLES.RENTER_RESIDENT]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_CREATE, FEATURES.VISITOR_READ, FEATURES.VISITOR_UPDATE, FEATURES.VISITOR_DELETE,
    FEATURES.GATE_PASS_MANAGEMENT, FEATURES.GATE_PASS_CREATE, FEATURES.GATE_PASS_READ,
    FEATURES.BILLING_MANAGEMENT, FEATURES.BILLING_READ,
    FEATURES.FACILITY_MANAGEMENT, FEATURES.FACILITY_READ, FEATURES.FACILITY_BOOKING,
    FEATURES.PARKING_MANAGEMENT, FEATURES.PARKING_READ,
    FEATURES.NOTICE_MANAGEMENT, FEATURES.NOTICE_READ,
    FEATURES.HELPDESK_MANAGEMENT, FEATURES.HELPDESK_CREATE, FEATURES.HELPDESK_READ, FEATURES.HELPDESK_UPDATE,
    FEATURES.MEETING_MANAGEMENT, FEATURES.MEETING_READ,
    FEATURES.DASHBOARD_RESIDENT,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE,
  ],
  
  [USER_ROLES.MEMBER_RESIDENT]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_CREATE, FEATURES.VISITOR_READ,
    FEATURES.GATE_PASS_MANAGEMENT, FEATURES.GATE_PASS_READ,
    FEATURES.BILLING_MANAGEMENT, FEATURES.BILLING_READ,
    FEATURES.FACILITY_MANAGEMENT, FEATURES.FACILITY_READ, FEATURES.FACILITY_BOOKING,
    FEATURES.PARKING_MANAGEMENT, FEATURES.PARKING_READ,
    FEATURES.NOTICE_MANAGEMENT, FEATURES.NOTICE_READ,
    FEATURES.HELPDESK_MANAGEMENT, FEATURES.HELPDESK_CREATE, FEATURES.HELPDESK_READ,
    FEATURES.MEETING_MANAGEMENT, FEATURES.MEETING_READ,
    FEATURES.DASHBOARD_RESIDENT,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE,
  ],
  
  [USER_ROLES.STAFF]: [
    FEATURES.VISITOR_MANAGEMENT, FEATURES.VISITOR_READ,
    FEATURES.HELPDESK_MANAGEMENT, FEATURES.HELPDESK_CREATE, FEATURES.HELPDESK_READ,
    FEATURES.SOS_MANAGEMENT, FEATURES.SOS_CREATE,
  ],
  
  [USER_ROLES.API_SYSTEM]: Object.values(FEATURES), // All permissions for API access
} as const;


